### ISSUE TITLE
Please fix the build

### ISSUE THREAD

**Issue by butterthebuddha** [mivanit/python-project-makefile-template#1]
<img width="983" alt="Screenshot 2024-07-06 at 3 05 52 PM" src="https://github.com/mivanit/python-project-makefile-template/assets/5279150/069a2a0f-18b2-462c-8fc5-83098926ed07">

Thanks, much appreciated

**Comment by mivanit** [comment]
fixed as of [v0.0.2](https://github.com/mivanit/python-project-makefile-template/releases/tag/v0.0.2)
